### ISSUE TITLE
Highlight matching words from query in each search result

### ISSUE THREAD

**Issue by ypk4** [TusharAgey/IR_Crawler#19]
Highlight the words in each search result and its summary that match with the words in the query

**Comment by TusharAgey** [comment]
we can go through this for highlighting: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

**Comment by TusharAgey** [comment]
and this: https://www.elastic.co/guide/en/elasticsearch/guide/current/highlighting-intro.html

**Comment by Mitali13** [comment]
We are on it.

**Comment by Mitali13** [comment]
Issue Solved!

**Comment by TusharAgey** [comment]
Please send a pull request.

**Comment by ypk4** [comment]
Closed
