### ISSUE TITLE
UI for Crawler

### ISSUE THREAD

**Issue by TusharAgey** [TusharAgey/IR_Crawler#2]
Create an UI for crawler where user can provide the seed url and a button to start crawling

**Comment by ypk4** [comment]
Let this be lowest priority and urgency issue.

**Comment by ypk4** [comment]
UI i.e. Drupal plugin for search engine

**Comment by TusharAgey** [comment]
No need of UI for crawler. We have created UI for Drupal Plugin as a search engine.

**Comment by ypk4** [comment]
Yayy!!
